[package]
name = "stim"
version = "1.2.0"
edition = "2024"

[dependencies]
serde_json = "1.0.145"
crossterm = "0.29.0"
serde = { version = "1.0.226", features = ["derive"] }
lofty = "0.22.4"
ratatui = "0.29.0"
rodio = "0.21.1"
walkdir = "2.5.0"
dirs = "6.0.0"
rand = "0.9.2"
